### ISSUE TITLE
Use custom container image

### ISSUE THREAD

**Issue by astj** [aereal/cdk-mackerel-container-agent#19]
I'd like to use custom container image instead of default mackerel/mackerel-container-agent, to include some custom metrics plugins to the image.
Currently this Construct doesn't support overriding image.

**Comment by astj** [comment]
@aereal What do you think?
Though extending everything will result :boom: , I think this extension is reasonable.

**Comment by aereal** [comment]
@astj LGTM!

**Comment by astj** [comment]
Fixed by #64
